name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  https:
    name: Ensure no-TLS snapshot usage
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Ensure http://snapshot.debian.org (https://github.com/debuerreotype/debuerreotype/pull/119#issuecomment-901457009)
        run: |
          rm .github/workflows/ci.yml # this file itself will always be a match, but it's the only valid one 👀
          if grep -rn 'https://snapshot.debian.org'; then
            exit 1
          fi

  test:
    strategy:
      matrix:
        include:
          # qemu-debootstrap testing
          - { ARCH: loong64, SUITE: unstable, CODENAME: "trixie", TIMESTAMP: "2025-08-01T00:00:00Z", SHA256: "" }
          - { ARCH: loong64, SUITE: unstable, CODENAME: "forky",  TIMESTAMP: "today 00:00:00",       SHA256: "" }
      fail-fast: false
    name: Test ${{ matrix.DISTRO && format('{0} ', matrix.DISTRO) }}${{ matrix.SUITE }}${{ matrix.CODENAME && format(' ({0})', matrix.CODENAME) }}${{ matrix.ARCH && format(' [{0}]', matrix.ARCH) }}${{ matrix.TIMESTAMP && format(' at {0}', matrix.TIMESTAMP) }}
    runs-on: ubuntu-24.04
    env: ${{ matrix }}
    steps:

      - uses: actions/checkout@v4

      - name: Prepare Environment
        run: |
          if [ -n "${ARCH:-}" ]; then
            sudo apt-get update -qq
            sudo apt-get install -yqq binfmt-support qemu-user-static
          fi
          docker run -d --name squignix --restart always tianon/squignix
          git clone --depth 1 https://github.com/tianon/pgp-happy-eyeballs.git ~/phe
          ~/phe/hack-my-builds.sh
          rm -rf ~/phe

          case "${{ matrix.CODENAME }}" in
            "trixie")
              sed -i 's/echo "URIs: $mirror"/echo "URIs: ${deb822Snapshots["$mirror"]}"/g' scripts/debuerreotype-debian-sources-list
              ;;
          esac

      - name: Build
        run: |
          "./.validate-${DISTRO:-debian}.sh"

      - name: Diff
        run: |
          cd validate

          ls -al

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: validate-${{ matrix.ARCH }}-${{ matrix.CODENAME }}
          path: validate/
